-- PostgreSQL 전환 시 새 DB에 적용하는 member 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE member_social_accounts(
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    member_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    social_id VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    social_provider VARCHAR(255) NOT NULL CHECK (social_provider IN ('GOOGLE', 'KAKAO'))
);

ALTER TABLE member_social_accounts ADD CONSTRAINT pk_member_social_accounts PRIMARY KEY(id);

CREATE TABLE members(
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    updated_by VARCHAR(255),
    role VARCHAR(255) CHECK (role IN ('ADMIN', 'MEMBER'))
);

ALTER TABLE members ADD CONSTRAINT pk_members PRIMARY KEY(id);

ALTER TABLE member_social_accounts ADD CONSTRAINT uk_member_social_accounts_social_provider_social_id UNIQUE (social_provider, social_id);

ALTER TABLE members ADD CONSTRAINT uk_members_email UNIQUE (email);

ALTER TABLE member_social_accounts ADD CONSTRAINT uk_member_social_accounts_member_id_social_provider UNIQUE (member_id, social_provider);

ALTER TABLE member_social_accounts ADD CONSTRAINT fk_member_social_accounts_member FOREIGN KEY(member_id) REFERENCES members(id);
