-- PostgreSQL 전환 시 새 DB에 적용하는 venue 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE seats(
    floor INTEGER NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    venue_id BIGINT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    row_no VARCHAR(255) NOT NULL,
    seat_no VARCHAR(255) NOT NULL,
    section VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255)
);

ALTER TABLE seats ADD CONSTRAINT pk_seats PRIMARY KEY(id);

CREATE UNIQUE INDEX uk_seats_venue_seat_address ON seats(venue_id, floor, section, row_no, seat_no);

CREATE TABLE venues(
    gap_x DOUBLE PRECISION,
    gap_y DOUBLE PRECISION,
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    seat_diameter DOUBLE PRECISION NOT NULL,
    view_box_height INTEGER NOT NULL,
    view_box_width INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    address VARCHAR(255),
    address_detail VARCHAR(255),
    created_by VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    name VARCHAR(255),
    phone VARCHAR(255),
    updated_by VARCHAR(255),
    zip_code VARCHAR(255),
    region VARCHAR(255) CHECK (region IN ('CHUNGCHEONG', 'GANGWON', 'GYEONGGI', 'GYEONGSANG', 'INCHEON', 'JEJU', 'JEOLLA', 'SEOUL'))
);

ALTER TABLE venues ADD CONSTRAINT pk_venues PRIMARY KEY(id);

ALTER TABLE seats ADD CONSTRAINT fk_seats_venue FOREIGN KEY(venue_id) REFERENCES venues(id);
