-- ticket-domain-module-redesign Phase 3 Task 7(ADR 0005): Order/OrderSeat가 주문 생성 시점의 catalog
-- 표시값을 snapshot으로 남긴다. catalog 값이 나중에 바뀌어도 이미 만든 주문 상세가 바뀌지 않게
-- 하기 위해서다. 동시에 Payment 실패는 더 이상 Order를 끝내는 사건이 아니므로(ADR 0005 결정 5)
-- payment_failed_at 컬럼을 제거한다.
--
-- ORDERS/ORDER_SEATS는 pre-Flyway baseline table이라(docs/operations.md 참고), 이 table 자체가 없는
-- 환경(BookingModuleSlicingSchemaTest/OracleMigrationCompatibilityTest의 최소 baseline 등)에서는
-- no-op이어야 한다. ORDER_SEATS는 그 baseline에도 order_id 컬럼 하나짜리로 존재하므로(__root V4가
-- 참조), unique 제약/색인은 performance_seat_id 컬럼이 실제로 있을 때만 추가한다.

EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ADD show_title_snapshot VARCHAR(1000)'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ADD performance_start_at_snapshot TIMESTAMP'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ADD venue_name_snapshot VARCHAR(255)'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT '
        UPDATE ORDERS
        SET show_title_snapshot = ''UNKNOWN'',
            performance_start_at_snapshot = created_at,
            venue_name_snapshot = ''UNKNOWN''
        WHERE show_title_snapshot IS NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ALTER COLUMN show_title_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ALTER COLUMN performance_start_at_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS ALTER COLUMN venue_name_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDERS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');

EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDERS DROP COLUMN payment_failed_at'
    FROM DUAL WHERE EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'ORDERS' AND COLUMN_NAME = 'PAYMENT_FAILED_AT'
    )
), 'DROP TABLE IF EXISTS __noop_migration_marker__');

EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ADD grade_code_snapshot VARCHAR(255)'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ADD grade_name_snapshot VARCHAR(255)'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ADD seat_label_snapshot VARCHAR(500)'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT '
        UPDATE ORDER_SEATS
        SET grade_code_snapshot = ''UNKNOWN'',
            grade_name_snapshot = ''UNKNOWN'',
            seat_label_snapshot = ''UNKNOWN''
        WHERE grade_code_snapshot IS NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ALTER COLUMN grade_code_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ALTER COLUMN grade_name_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ALTER COLUMN seat_label_snapshot SET NOT NULL'
    FROM DUAL WHERE EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_SEATS')
), 'DROP TABLE IF EXISTS __noop_migration_marker__');

EXECUTE IMMEDIATE COALESCE((
    SELECT 'ALTER TABLE ORDER_SEATS ADD CONSTRAINT UK_ORDER_SEATS_ORDER_PERF_SEAT UNIQUE (order_id, performance_seat_id)'
    FROM DUAL WHERE EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'ORDER_SEATS' AND COLUMN_NAME = 'PERFORMANCE_SEAT_ID'
    )
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
EXECUTE IMMEDIATE COALESCE((
    SELECT 'CREATE INDEX IDX_ORDER_SEATS_PERF_SEAT_ID ON ORDER_SEATS (performance_seat_id)'
    FROM DUAL WHERE EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'ORDER_SEATS' AND COLUMN_NAME = 'PERFORMANCE_SEAT_ID'
    )
), 'DROP TABLE IF EXISTS __noop_migration_marker__');
