-- ADR 0005: Ticket은 결제 성공으로 확정된 OrderSeat에 대해 발급되는 입장 권리다
-- (OrderSeat 1 : 0..1 Ticket). 원래 별도 ticketing module의 V1이었으나 Ticket이 booking으로
-- 흡수되며 booking V5로 옮겼다. owner_member_id는 member module에 대한 scalar 컬럼이라 FK를 걸지
-- 않고(cross-module 물리 FK 금지, ADR 0003), order_seat_id도 기존 관례대로 scalar 컬럼으로 둔다.
CREATE TABLE TICKETS (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_key VARCHAR2(64 CHAR) NOT NULL,
    order_seat_id NUMBER(19, 0) NOT NULL,
    owner_member_id NUMBER(19, 0) NOT NULL,
    status VARCHAR2(16 CHAR) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255 CHAR) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR2(255 CHAR),
    CONSTRAINT uk_tickets_ticket_key UNIQUE (ticket_key),
    CONSTRAINT uk_tickets_order_seat_id UNIQUE (order_seat_id)
);

CREATE INDEX idx_tickets_owner_member_status ON TICKETS (owner_member_id, status);
