-- ADR 0005: Payment는 Order에 대한 한 번의 결제 시도다(Order 1 : 0..N Payment). payment는
-- booking을 참조하지 않는 독립 module이므로 order_id는 scalar 컬럼일 뿐 FK를 걸지 않는다
-- (cross-module 물리 FK 금지, ADR 0003/0005).
CREATE TABLE PAYMENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_key VARCHAR(64) NOT NULL,
    attempt_no INTEGER NOT NULL,
    provider VARCHAR(32) NOT NULL,
    method VARCHAR(32) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_payment_key VARCHAR(64),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    failure_code VARCHAR(64),
    failure_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT uk_payments_payment_key UNIQUE (payment_key),
    CONSTRAINT uk_payments_order_attempt UNIQUE (order_id, attempt_no),
    CONSTRAINT uk_payments_provider_payment_key UNIQUE (provider_payment_key),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0)
);

CREATE INDEX idx_payments_order_status ON PAYMENTS (order_id, status);
