-- Flyway 도입 이전(pre-Flyway) 기준 스키마다. 빈 DB에서 migration만으로 현재 스키마를 만들기 위해 둔다.
--
-- 운영은 이 파일을 실행하지 않는다. 운영 flyway_schema_history에는 version 1 BASELINE 행이 있어
-- (2026-05 Flyway 도입 때 기존 스키마를 baseline으로 등록) Flyway가 이 파일을 baseline 이하로 보고 건너뛴다.
-- 빈 DB(로컬·테스트)에서만 __root V2보다 먼저 실행된다.
--
-- 모양은 "지금 entity"가 아니라 "뒤따르는 migration이 전제하는 옛 모양"이다. 뒤 migration 중 일부가
-- 존재 확인 없이 컬럼·제약을 추가하므로(booking V3·V4 등), 그 대상은 여기서 빼 두고 해당 migration이 만든다.
--   - PERFORMANCES: 판매정책 컬럼 4개를 둔다(booking V6가 옮기고 지운다).
--   - PERFORMANCE_SEATS: performance_grade_id·unit_price·version이 없다(show V6·booking V3가 추가한다).
--   - ORDERS·ORDER_SEATS: 표시 snapshot 컬럼과 주문좌석 유니크가 없다(booking V4가 추가한다).
--   - 좌석 주소 유니크(venue V1), 찜 유니크(like V3), 회차좌석 유니크(root V3), 주문좌석 order_id 인덱스(root V4)는 각 migration이 만든다.
--   - GRADES·PERFORMANCE_GRADES(show V4), TICKETS(booking V5), BOOKING_PERFORMANCE_SALES_POLICIES(booking V6),
--     PAYMENTS(payment V1), EVENT_PUBLICATION(root V8)은 여기 없다.
-- 원본은 현재 entity 매핑에서 Hibernate schema export로 뽑은 DDL이다. 이 파일만이 아니라 전체 migration을 거친
-- 결과가 entity와 맞는지를 MigrationChainSchemaTest가 고정한다.

create table categories (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        code varchar(255) not null unique,
        created_by varchar(255) not null,
        name varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

create table genres (
        category_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        code varchar(255) not null unique,
        created_by varchar(255) not null,
        name varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

create table hold_history (
        created_at timestamp(6) not null,
        expires_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        occurred_at timestamp(6) not null,
        performance_id bigint not null,
        performance_seat_id bigint not null,
        seat_id bigint not null,
        updated_at timestamp(6),
        hold_key varchar(64) not null,
        created_by varchar(255) not null,
        updated_by varchar(255),
        event_type enum ('CANCELED','CONFIRMED','CREATED','EXPIRED') not null,
        release_reason enum ('ORDER_EXPIRED','PAYMENT_CONFIRMED','PAYMENT_FAILED','TTL_EXPIRED','USER_CANCELED'),
        primary key (id)
    );

create table likes (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        target_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        updated_by varchar(255),
        like_type enum ('SHOW') not null,
        primary key (id)
    );

create table member_social_accounts (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        social_id varchar(255) not null,
        updated_by varchar(255),
        social_provider enum ('GOOGLE','KAKAO') not null,
        primary key (id),
        unique (social_provider, social_id),
        unique (member_id, social_provider)
    );

create table members (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        updated_by varchar(255),
        role enum ('ADMIN','MEMBER'),
        primary key (id),
        unique (email)
    );

create table order_seats (
        price numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        performance_seat_id bigint not null,
        seat_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

create table orders (
        total_amount numeric(19,2) not null,
        canceled_at timestamp(6),
        confirmed_at timestamp(6),
        created_at timestamp(6) not null,
        expired_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        performance_id bigint not null,
        updated_at timestamp(6),
        order_key varchar(40) not null unique,
        hold_key varchar(64) not null unique,
        created_by varchar(255) not null,
        updated_by varchar(255),
        status enum ('CANCELED','CONFIRMED','EXPIRED','PENDING') not null,
        primary key (id)
    );

create table performance_seats (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        performance_id bigint not null,
        seat_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        updated_by varchar(255),
        state enum ('AVAILABLE','RESERVED'),
        primary key (id)
    );

create table performances (
        created_at timestamp(6) not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        performance_no bigint,
        show_id bigint,
        start_time timestamp(6),
        updated_at timestamp(6),
        created_by varchar(255) not null,
        updated_by varchar(255),
        order_open_time timestamp(6),
        order_close_time timestamp(6),
        max_can_hold_count integer,
        hold_time integer,
        primary key (id)
    );

create table performers (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        name varchar(255),
        profile_image_url varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

create table seats (
        floor integer not null,
        x float(53) not null,
        y float(53) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        venue_id bigint not null,
        created_by varchar(255) not null,
        row_no varchar(255) not null,
        seat_no varchar(255) not null,
        section varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

create table show_genres (
        created_at timestamp(6) not null,
        genre_id bigint not null,
        id bigint generated by default as identity,
        show_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

create table shows (
        end_date date,
        running_minutes integer,
        start_date date,
        created_at timestamp(6) not null,
        display_sale_ends_at timestamp(6),
        display_sale_starts_at timestamp(6),
        id bigint generated by default as identity,
        performer_id bigint,
        updated_at timestamp(6),
        venue_id bigint not null,
        view_count bigint not null,
        sub_title varchar(500),
        title varchar(1000),
        created_by varchar(255) not null,
        image varchar(255),
        updated_by varchar(255),
        display_sale_type enum ('EXCLUSIVE','GENERAL'),
        info CLOB,
        primary key (id)
    );

create table venues (
        gap_x float(53),
        gap_y float(53),
        latitude numeric(10,8),
        longitude numeric(11,8),
        seat_diameter float(53) not null,
        view_box_height integer not null,
        view_box_width integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        address varchar(255),
        address_detail varchar(255),
        created_by varchar(255) not null,
        image_url varchar(255),
        name varchar(255),
        phone varchar(255),
        updated_by varchar(255),
        zip_code varchar(255),
        region enum ('CHUNGCHEONG','GANGWON','GYEONGGI','GYEONGSANG','INCHEON','JEJU','JEOLLA','SEOUL'),
        primary key (id)
    );

create index IDX_HOLD_HISTORY_HOLD_KEY
       on hold_history (hold_key);

create index IDX_LIKES_MEMBER_ID_ID
       on likes (member_id, id);

create index IDX_LIKES_TARGET
       on likes (like_type, target_id);

create index IDX_ORDERS_MEMBER_PERFORMANCE_STATUS
       on orders (member_id, performance_id, status);

alter table member_social_accounts
       add constraint FK_MEMBER_SOCIAL_ACCOUNTS_MEMBER
       foreign key (member_id)
       references members;

alter table order_seats
       add constraint FK_ORDER_SEATS_ORDER
       foreign key (order_id)
       references orders;
