-- ADR 0005: Grade는 재사용 가능한 등급 코드/이름만 갖고 가격이 없다. PerformanceGrade가 회차별
-- 가격·표시 순서를 갖는 연결 entity이며 가격의 원본이다
-- (PerformanceGrade.price -> PerformanceSeat.unitPrice -> OrderSeat.unitPrice snapshot 체인).
-- PERFORMANCES table은 어떤 Flyway migration도 만들지 않은 pre-Flyway baseline이라(docs/operations.md
-- 참고) 이미 존재한다는 전제로 FK를 건다.
CREATE TABLE GRADES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT uk_grades_code UNIQUE (code)
);

CREATE TABLE PERFORMANCE_GRADES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_performance_grades_performance FOREIGN KEY (performance_id) REFERENCES PERFORMANCES (id),
    CONSTRAINT fk_performance_grades_grade FOREIGN KEY (grade_id) REFERENCES GRADES (id),
    CONSTRAINT uk_performance_grades_performance_grade UNIQUE (performance_id, grade_id),
    CONSTRAINT ck_performance_grades_price CHECK (price >= 0)
);

CREATE INDEX idx_performance_grades_perf_sort ON PERFORMANCE_GRADES (performance_id, sort_order);
