-- PostgreSQL 전환 시 새 DB에 적용하는 booking 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE hold_history(
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    member_id BIGINT NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    performance_id BIGINT NOT NULL,
    performance_seat_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    hold_key VARCHAR(64) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    event_type VARCHAR(255) NOT NULL CHECK (event_type IN ('CANCELED', 'CONFIRMED', 'CREATED', 'EXPIRED')),
    release_reason VARCHAR(255) CHECK (release_reason IN ('ORDER_EXPIRED', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'TTL_EXPIRED', 'USER_CANCELED'))
);

ALTER TABLE hold_history ADD CONSTRAINT pk_hold_history PRIMARY KEY(id);

CREATE TABLE order_seats(
    price NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    order_id BIGINT NOT NULL,
    performance_seat_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    grade_code_snapshot VARCHAR(255) NOT NULL,
    grade_name_snapshot VARCHAR(255) NOT NULL,
    seat_label_snapshot VARCHAR(500) NOT NULL
);

ALTER TABLE order_seats ADD CONSTRAINT pk_order_seats PRIMARY KEY(id);

CREATE TABLE tickets(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    ticket_key VARCHAR(64) NOT NULL,
    order_seat_id BIGINT NOT NULL,
    owner_member_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

ALTER TABLE tickets ADD CONSTRAINT pk_tickets PRIMARY KEY(id);

CREATE TABLE orders(
    total_amount NUMERIC(19, 2) NOT NULL,
    canceled_at TIMESTAMP(6),
    confirmed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    expired_at TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    member_id BIGINT NOT NULL,
    performance_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    order_key VARCHAR(40) NOT NULL,
    hold_key VARCHAR(64) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('CANCELED', 'CONFIRMED', 'EXPIRED', 'PENDING')),
    show_title_snapshot VARCHAR(1000) NOT NULL,
    performance_start_at_snapshot TIMESTAMP NOT NULL,
    venue_name_snapshot VARCHAR(255) NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT pk_orders PRIMARY KEY(id);

CREATE TABLE performance_seats(
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    performance_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    state VARCHAR(255) CHECK (state IN ('AVAILABLE', 'RESERVED')),
    performance_grade_id BIGINT NOT NULL,
    unit_price DECIMAL(19, 2) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL
);

ALTER TABLE performance_seats ADD CONSTRAINT pk_performance_seats PRIMARY KEY(id);

CREATE UNIQUE INDEX uk_performance_seats_performance_seat ON performance_seats(performance_id, seat_id);

CREATE TABLE booking_performance_sales_policies(
    performance_id BIGINT NOT NULL,
    order_opens_at TIMESTAMP NOT NULL,
    order_closes_at TIMESTAMP NOT NULL,
    max_hold_seat_count INTEGER,
    hold_duration_seconds BIGINT NOT NULL,
    queue_mode VARCHAR(20),
    queue_level VARCHAR(20),
    preopen_queue_starts_at TIMESTAMP,
    waiting_room_message VARCHAR(255),
    queue_policy_reason VARCHAR(255),
    version BIGINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

ALTER TABLE booking_performance_sales_policies ADD CONSTRAINT pk_booking_performance_sales_policies PRIMARY KEY(performance_id);

ALTER TABLE booking_performance_sales_policies ADD CONSTRAINT ck_booking_perf_sales_policies_max_hold CHECK((max_hold_seat_count IS NULL)
    OR (max_hold_seat_count >= 2));

ALTER TABLE booking_performance_sales_policies ADD CONSTRAINT ck_booking_perf_sales_policies_hold_duration CHECK(hold_duration_seconds > CAST(0 AS BIGINT));

ALTER TABLE booking_performance_sales_policies ADD CONSTRAINT ck_booking_perf_sales_policies_window CHECK(order_opens_at < order_closes_at);

ALTER TABLE performance_seats ADD CONSTRAINT ck_performance_seats_unit_price CHECK(unit_price >= CAST(0 AS NUMERIC(1)));

ALTER TABLE orders ADD CONSTRAINT uk_orders_order_key UNIQUE (order_key);

ALTER TABLE order_seats ADD CONSTRAINT uk_order_seats_order_perf_seat UNIQUE (order_id, performance_seat_id);

ALTER TABLE tickets ADD CONSTRAINT uk_tickets_ticket_key UNIQUE (ticket_key);

ALTER TABLE tickets ADD CONSTRAINT uk_tickets_order_seat_id UNIQUE (order_seat_id);

ALTER TABLE orders ADD CONSTRAINT uk_orders_hold_key UNIQUE (hold_key);

ALTER TABLE order_seats ADD CONSTRAINT fk_order_seats_order FOREIGN KEY(order_id) REFERENCES orders(id);
