-- PostgreSQL 전환 시 새 DB에 적용하는 payment 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE payments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    order_id BIGINT NOT NULL,
    payment_key VARCHAR(64) NOT NULL,
    attempt_no INTEGER NOT NULL,
    provider VARCHAR(32) NOT NULL,
    method VARCHAR(32) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_payment_key VARCHAR(64),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    failure_code VARCHAR(64),
    failure_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

ALTER TABLE payments ADD CONSTRAINT pk_payments PRIMARY KEY(id);

ALTER TABLE payments ADD CONSTRAINT ck_payments_amount CHECK(amount >= CAST(0 AS NUMERIC(1)));

ALTER TABLE payments ADD CONSTRAINT uk_payments_order_attempt UNIQUE (order_id, attempt_no);

ALTER TABLE payments ADD CONSTRAINT uk_payments_payment_key UNIQUE (payment_key);

ALTER TABLE payments ADD CONSTRAINT uk_payments_provider_payment_key UNIQUE (provider_payment_key);
