-- PostgreSQL 전환 시 새 DB에 적용하는 like 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE likes(
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    member_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    like_type VARCHAR(255) NOT NULL CHECK (like_type IN ('SHOW'))
);

ALTER TABLE likes ADD CONSTRAINT pk_likes PRIMARY KEY(id);

ALTER TABLE likes ADD CONSTRAINT uk_likes_member_target UNIQUE (member_id, like_type, target_id);
