package com.ticket.bootstrap.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.modulith.core.ApplicationModuleIdentifier;
import org.springframework.modulith.core.ApplicationModuleIdentifiers;
import org.springframework.modulith.runtime.flyway.MigrationFilter;
import org.springframework.modulith.runtime.flyway.SpringModulithFlywayMigrationStrategy;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.oracle.OracleContainer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Task 11 Step 7: 저장소에 기존 Oracle Testcontainers/profile 인프라가 없어(확인함:
 * {@code build.gradle}에 Oracle Testcontainers 모듈이 전혀 없었다) 이 Task에서 새로 추가한다.
 * 실제 Oracle(Testcontainers {@code gvenzl/oracle-free}) 위에서 {@code __root}(V2~V8, 특히 V8의
 * RAW(16)/CHECK 제약)와 독립된 {@code booking} module 자체 이력(V1의 PL/SQL 동적 FK 제거, V2의
 * outbox table 제거)의 Oracle 방언 migration이 문법 오류 없이 실제로 적용되는지 검증한다.
 * {@code booking}은 {@code spring.modulith.runtime.flyway-enabled}로 자신만의
 * {@code flyway_schema_history_booking}을 가지므로 root의 V-번호와 겹치지 않는다.
 *
 * <p>Docker가 없는 환경에서는 이 클래스 전체가 Testcontainers에 의해 자동으로 건너뛰어진다
 * ({@code @Testcontainers}의 기본 동작).
 */
@Testcontainers(disabledWithoutDocker = true)
class OracleMigrationCompatibilityTest {

    private static final OracleContainer ORACLE = new OracleContainer("gvenzl/oracle-free:23-slim");

    @BeforeAll
    static void startContainer() {
        ORACLE.start();
    }

    @AfterAll
    static void stopContainer() {
        ORACLE.stop();
    }

    @Test
    void root_and_booking_oracle_migrations_apply_without_syntax_errors() throws Exception {
        createLegacyBaselineSchema();
        applyRootOnlyForQueuePoliciesTable();

        final Flyway baseFlyway = Flyway.configure()
                .dataSource(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword())
                .locations(
                        "classpath:db/migration",
                        "classpath:db/migration-vendor/oracle"
                )
                .load();

        final ApplicationModuleIdentifiers identifiers =
                ApplicationModuleIdentifiers.of(List.of(ApplicationModuleIdentifier.of("booking")));

        new SpringModulithFlywayMigrationStrategy(identifiers, MigrationFilter.USE_ALL).migrate(baseFlyway);

        try (Connection connection = connect()) {
            assertThat(tableExists(connection, "EVENT_PUBLICATION")).isTrue();
            assertThat(tableExists(connection, "EVENT_PUBLICATION_ARCHIVE")).isTrue();
            assertThat(tableExists(connection, "ORDER_HOLD_RELEASE_OUTBOX")).isFalse();
            assertThat(tableExists(connection, "ORDER_HOLD_CREATION_OUTBOX")).isFalse();
            assertThat(importedKeyTables(connection, "PERFORMANCE_SEATS")).isEmpty();

            // ADR 0006 "Performance의 책임 혼재" A2: booking V6가 실제 Oracle 방언에서도 정책
            // 소유권 이관(backfill + drop)을 문법 오류 없이 수행하는지 확인한다.
            assertThat(tableExists(connection, "BOOKING_PERFORMANCE_SALES_POLICIES")).isTrue();
            assertThat(tableExists(connection, "PERFORMANCE_QUEUE_POLICIES")).isFalse();
            assertThat(hasColumn(connection, "PERFORMANCES", "ORDER_OPEN_TIME")).isFalse();
            try (Statement statement = connection.createStatement();
                 ResultSet row = statement.executeQuery(
                         "SELECT hold_duration_seconds, queue_mode FROM BOOKING_PERFORMANCE_SALES_POLICIES WHERE performance_id = 1")) {
                assertThat(row.next()).isTrue();
                assertThat(row.getLong("hold_duration_seconds")).isEqualTo(600);
                assertThat(row.getString("queue_mode")).isEqualTo("FORCE_OFF");
            }
        }
    }

    private void createLegacyBaselineSchema() throws SQLException {
        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE performances (
                      id NUMBER(19,0) PRIMARY KEY,
                      order_open_time TIMESTAMP,
                      order_close_time TIMESTAMP,
                      max_can_hold_count NUMBER(10,0),
                      hold_time NUMBER(10,0)
                    )
                    """);
            statement.execute("CREATE TABLE seats (id NUMBER(19,0) PRIMARY KEY)");
            statement.execute(
                    "CREATE TABLE performance_seats (" +
                    "  id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "  performance_id NUMBER(19,0) NOT NULL, " +
                    "  seat_id NUMBER(19,0) NOT NULL, " +
                    "  CONSTRAINT legacy_fk_performance FOREIGN KEY (performance_id) REFERENCES performances(id), " +
                    "  CONSTRAINT legacy_fk_seat FOREIGN KEY (seat_id) REFERENCES seats(id)" +
                    ")");
            statement.execute("CREATE TABLE order_seats (order_id NUMBER(19,0) NOT NULL)");
            statement.execute(
                    "INSERT INTO performances (id, order_open_time, order_close_time, max_can_hold_count, hold_time) "
                    + "VALUES (1, TIMESTAMP '2026-05-01 10:00:00', TIMESTAMP '2026-06-01 10:00:00', 4, NULL)");
        }
    }

    private void applyRootOnlyForQueuePoliciesTable() throws SQLException {
        final Flyway rootOnlyFlyway = Flyway.configure()
                .dataSource(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword())
                .locations("classpath:db/migration", "classpath:db/migration-vendor/oracle")
                .load();
        new SpringModulithFlywayMigrationStrategy(ApplicationModuleIdentifiers.of(List.of()), MigrationFilter.USE_ALL)
                .migrate(rootOnlyFlyway);

        try (Connection connection = connect();
             Statement statement = connection.createStatement()) {
            statement.execute(
                    "INSERT INTO performance_queue_policies (performance_id, queue_mode, queue_level, created_at, created_by) "
                    + "VALUES (1, 'FORCE_OFF', 'LEVEL_1', SYSTIMESTAMP, 'test')");
        }
    }

    private Connection connect() throws SQLException {
        return DriverManager.getConnection(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword());
    }

    private boolean tableExists(final Connection connection, final String tableName) throws SQLException {
        try (ResultSet tables = connection.getMetaData().getTables(null, null, tableName, new String[]{"TABLE"})) {
            return tables.next();
        }
    }

    private boolean hasColumn(final Connection connection, final String table, final String column) throws SQLException {
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, table, column)) {
            return columns.next();
        }
    }

    private Set<String> importedKeyTables(final Connection connection, final String tableName) throws SQLException {
        final Set<String> names = new HashSet<>();
        try (ResultSet keys = connection.getMetaData().getImportedKeys(null, null, tableName)) {
            while (keys.next()) {
                names.add(keys.getString("FK_NAME"));
            }
        }
        return names;
    }
}
