package com.ticket.bootstrap.migration;

import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Task 4(ADR 0005): show module의 GRADES/PERFORMANCE_GRADES 신규 migration(V4)이 실제로 만드는
 * schema를 검증한다. {@code __root}와 show의 migration만(다른 module 없이) 적용해,
 * GRADES/PERFORMANCE_GRADES table과 그 제약(가격 CHECK, {@code (performance_id, grade_id)} UNIQUE,
 * FK)이 기대한 대로 동작하는지 실제 INSERT로 확인한다.
 *
 * <p>PERFORMANCE_GRADES는 show 안에서 Performance를 JPA {@code @ManyToOne}으로 참조하므로
 * (같은 aggregate 안이라 객체 참조를 유지한다 — Grade는 다른 aggregate라 {@code gradeId} scalar다),
 * {@link BookingModuleSlicingSchemaTest}처럼 Hibernate SchemaValidator 단독으로 검증하려면
 * Performance에 딸린 Show/Venue/Performer 전체 mapping을 함께 올려야 한다.
 * 그 전체 그래프를 흉내 낸 legacy baseline을 새로 만드는 대신, 실제 migration이 만든 schema에 직접
 * INSERT해 제약이 동작하는지 확인하는 쪽을 택했다 — 목적(제약이 실제로 걸리는지 확인)에는 이 쪽이
 * 더 직접적이다. Grade 엔티티 매핑 자체는 {@code GradeRepositoryAdapterTest}가
 * {@code ddl-auto=create-drop}로 검증한다({@code PerformanceGradeRepositoryAdapter}는 소비자가 없어
 * 제거됐고, 회차 등급 조회는 {@code QuerydslPerformanceGradeReadRepository}가 담당한다).
 */
class ShowGradeSchemaMigrationTest {

    private static final String URL =
            "jdbc:h2:mem:show-grade-schema-migration;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE";

    @Test
    void root와_show_migration만으로_GRADES와_PERFORMANCE_GRADES_schema를_만들고_제약이_동작한다() throws Exception {
        createLegacyPerformancesBaseline();
        // 다른 module의 migration은 이 DB에 전혀 적용하지 않는다 — __root와 show뿐이다.
        ModulithFlywayTestSupport.migrate(URL, List.of("show"));

        try (Connection connection = ModulithFlywayTestSupport.connect(URL)) {
            assertThat(ModulithFlywayTestSupport.tableExists(connection, "GRADES")).isTrue();
            assertThat(ModulithFlywayTestSupport.tableExists(connection, "PERFORMANCE_GRADES")).isTrue();

            insertPerformance(connection, 1L);
            insertPerformance(connection, 2L);
            long vipGradeId = insertGrade(connection, "VIP", "VIP석");

            // 같은 Grade를 여러 Performance가 재사용할 수 있고, 회차마다 가격이 다를 수 있다.
            insertPerformanceGrade(connection, 1L, vipGradeId, new BigDecimal("100000.00"), 1);
            insertPerformanceGrade(connection, 2L, vipGradeId, new BigDecimal("120000.00"), 1);

            // 같은 Performance에 같은 Grade가 중복되면 unique 제약 위반이다.
            assertThatThrownBy(() -> insertPerformanceGrade(connection, 1L, vipGradeId, new BigDecimal("999.00"), 2))
                    .isInstanceOf(SQLException.class);

            // 가격이 음수면 CHECK 제약 위반이다.
            long rGradeId = insertGrade(connection, "R", "R석");
            assertThatThrownBy(() -> insertPerformanceGrade(connection, 1L, rGradeId, new BigDecimal("-1.00"), 2))
                    .isInstanceOf(SQLException.class);
        }
    }

    /**
     * PERFORMANCES/SEATS/PERFORMANCE_SEATS/ORDER_SEATS는 어떤 Flyway migration도 만들지 않는
     * pre-Flyway baseline(docs/operations.md 참고)이다. {@code __root}의 기존 V3/V4가 이 table들을
     * 전제로 인덱스를 추가하므로, show만 골라 검증하더라도 root 이력이 요구하는 만큼은 재현해야
     * 한다({@link BookingModuleSlicingSchemaTest}의 baseline과 같다).
     */
    private void createLegacyPerformancesBaseline() throws Exception {
        try (Connection connection = ModulithFlywayTestSupport.connect(URL);
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE performances (id BIGINT PRIMARY KEY)");
            statement.execute("CREATE TABLE venues (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
            statement.execute(
                    "CREATE TABLE seats (" +
                    "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "  section VARCHAR(255) NOT NULL, row_no VARCHAR(255) NOT NULL, " +
                    "  seat_no VARCHAR(255) NOT NULL, floor INT NOT NULL, " +
                    "  x DOUBLE NOT NULL, y DOUBLE NOT NULL, " +
                    "  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL, " +
                    "  updated_at TIMESTAMP, updated_by VARCHAR(255)" +
                    ")");
            statement.execute(
                    "CREATE TABLE performance_seats (" +
                    "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "  performance_id BIGINT NOT NULL, " +
                    "  seat_id BIGINT NOT NULL, " +
                    "  state VARCHAR(255), " +
                    "  price DECIMAL(38, 2), " +
                    "  created_at TIMESTAMP NOT NULL, " +
                    "  created_by VARCHAR(255) NOT NULL, " +
                    "  updated_at TIMESTAMP, " +
                    "  updated_by VARCHAR(255)" +
                    ")");
            statement.execute("CREATE TABLE order_seats (order_id BIGINT NOT NULL)");
        }
    }

    private void insertPerformance(final Connection connection, final long id) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO performances (id) VALUES (?)")) {
            statement.setLong(1, id);
            statement.executeUpdate();
        }
    }

    private long insertGrade(final Connection connection, final String code, final String name) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO GRADES (code, name, created_at, created_by) VALUES (?, ?, CURRENT_TIMESTAMP, 'test')",
                Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, code);
            statement.setString(2, name);
            statement.executeUpdate();
            try (ResultSet keys = statement.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    private void insertPerformanceGrade(
            final Connection connection,
            final long performanceId,
            final long gradeId,
            final BigDecimal price,
            final int sortOrder
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO PERFORMANCE_GRADES (performance_id, grade_id, price, sort_order, created_at, created_by) "
                        + "VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, 'test')")) {
            statement.setLong(1, performanceId);
            statement.setLong(2, gradeId);
            statement.setBigDecimal(3, price);
            statement.setInt(4, sortOrder);
            statement.executeUpdate();
        }
    }
}
