-- ADR 0005: Payment는 Order에 대한 한 번의 결제 시도다(Order 1 : 0..N Payment). payment는
-- booking을 참조하지 않는 독립 module이므로 order_id는 scalar 컬럼일 뿐 FK를 걸지 않는다
-- (cross-module 물리 FK 금지, ADR 0003/0005).
CREATE TABLE PAYMENTS (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19, 0) NOT NULL,
    payment_key VARCHAR2(64 CHAR) NOT NULL,
    attempt_no NUMBER(10, 0) NOT NULL,
    provider VARCHAR2(32 CHAR) NOT NULL,
    method VARCHAR2(32 CHAR) NOT NULL,
    amount NUMBER(19, 2) NOT NULL,
    status VARCHAR2(16 CHAR) NOT NULL,
    provider_payment_key VARCHAR2(64 CHAR),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    failure_code VARCHAR2(64 CHAR),
    failure_message VARCHAR2(1000 CHAR),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255 CHAR) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR2(255 CHAR),
    CONSTRAINT uk_payments_payment_key UNIQUE (payment_key),
    CONSTRAINT uk_payments_order_attempt UNIQUE (order_id, attempt_no),
    CONSTRAINT uk_payments_provider_payment_key UNIQUE (provider_payment_key),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0)
);

CREATE INDEX idx_payments_order_status ON PAYMENTS (order_id, status);
