package com.ticket.seed.internal;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LoadTestFixtureSeederTest {

    private static final long ID_BASE = 910000000L;

    private EmbeddedDatabase database;
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        database = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .generateUniqueName(true)
                .build();
        jdbcTemplate = new JdbcTemplate(database);
        jdbcTemplate.execute("""
                CREATE TABLE venues (
                  id BIGINT PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), region VARCHAR(50),
                  address_detail VARCHAR(255), zip_code VARCHAR(20), latitude DOUBLE, longitude DOUBLE,
                  phone VARCHAR(50), image_url VARCHAR(500), view_box_width INT NOT NULL,
                  view_box_height INT NOT NULL, seat_diameter DOUBLE NOT NULL, gap_x DOUBLE, gap_y DOUBLE,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE shows (
                  id BIGINT PRIMARY KEY, title VARCHAR(255), sub_title VARCHAR(255), info VARCHAR(1000),
                  start_date DATE, end_date DATE, view_count BIGINT NOT NULL, sale_type VARCHAR(50),
                  sale_start_date TIMESTAMP, sale_end_date TIMESTAMP, image VARCHAR(500),
                  venue_id BIGINT, running_minutes INT, performer_id BIGINT,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE seats (
                  id BIGINT PRIMARY KEY, venue_id BIGINT NOT NULL, section VARCHAR(50) NOT NULL,
                  row_no VARCHAR(50) NOT NULL, seat_no VARCHAR(50) NOT NULL, floor INT NOT NULL,
                  x DOUBLE NOT NULL, y DOUBLE NOT NULL,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE show_grades (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, show_id BIGINT NOT NULL,
                  grade_code VARCHAR(50) NOT NULL, grade_name VARCHAR(50) NOT NULL,
                  price NUMERIC(19,2) NOT NULL, sort_order INT NOT NULL,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE show_seats (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, show_id BIGINT NOT NULL,
                  seat_id BIGINT NOT NULL, show_grade_id BIGINT NOT NULL,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE performances (
                  id BIGINT PRIMARY KEY, show_id BIGINT, performance_no INT,
                  start_time TIMESTAMP, end_time TIMESTAMP, order_open_time TIMESTAMP,
                  order_close_time TIMESTAMP, max_can_hold_count INT, hold_time INT,
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE performance_queue_policies (
                  performance_id BIGINT PRIMARY KEY, queue_mode VARCHAR(50), queue_level VARCHAR(50),
                  preopen_queue_start_at TIMESTAMP, waiting_room_message VARCHAR(500),
                  reason VARCHAR(500), created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE performance_seats (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, performance_id BIGINT NOT NULL,
                  seat_id BIGINT NOT NULL, state VARCHAR(50), price NUMERIC(19,2),
                  created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL)
                """);
    }

    @AfterEach
    void tearDown() {
        database.shutdown();
    }

    private LoadTestFixtureSeeder seeder(final boolean enabled, final int performanceCount) {
        return new LoadTestFixtureSeeder(jdbcTemplate, enabled, performanceCount);
    }

    private int count(final String sql) {
        final Integer value = jdbcTemplate.queryForObject(sql, Integer.class);
        return value == null ? 0 : value;
    }

    @Test
    void runsAfterTheSharedSeedLoader() {
        // 공용 시드는 FROM SHOWS s CROSS JOIN (VIP/R/S/A ...)로 그 시점의 모든 SHOWS를 훑는다.
        // 이 시더가 먼저 돌면 전용 show에 공용 등급이 덧붙어 grade_code가 중복되고 기동이 실패한다.
        final int sharedSeedOrder = SeedDataLoader.class.getAnnotation(Order.class).value();
        final int fixtureOrder = LoadTestFixtureSeeder.class.getAnnotation(Order.class).value();

        assertTrue(sharedSeedOrder < fixtureOrder,
                "LoadTestFixtureSeeder는 SeedDataLoader보다 뒤에 실행돼야 합니다. shared="
                        + sharedSeedOrder + ", fixture=" + fixtureOrder);
    }

    @Test
    void createsDedicatedShowSeatsAndPerformances() {
        seeder(true, 3).seedLoadTestFixture();

        assertEquals(1, count("SELECT COUNT(*) FROM venues WHERE id = " + (ID_BASE + 1)));
        assertEquals(1, count("SELECT COUNT(*) FROM shows WHERE id = " + (ID_BASE + 1)));
        assertEquals(2000, count("SELECT COUNT(*) FROM seats"));
        assertEquals(4, count("SELECT COUNT(*) FROM show_grades"));
        assertEquals(2000, count("SELECT COUNT(*) FROM show_seats"));
        assertEquals(3, count("SELECT COUNT(*) FROM performances"));
        assertEquals(6000, count("SELECT COUNT(*) FROM performance_seats"));
    }

    @Test
    void usesFixedIdRangeStartingAt910000001() {
        seeder(true, 2).seedLoadTestFixture();

        assertEquals(2000, count(
                "SELECT COUNT(*) FROM seats WHERE id BETWEEN 910000001 AND 910002000"));
        assertEquals(2, count(
                "SELECT COUNT(*) FROM performances WHERE id BETWEEN 910000001 AND 910000002"));
    }

    @Test
    void marksEveryPerformanceQueuePolicyAsForceOff() {
        seeder(true, 4).seedLoadTestFixture();

        assertEquals(4, count("SELECT COUNT(*) FROM performance_queue_policies"));
        assertEquals(4, count(
                "SELECT COUNT(*) FROM performance_queue_policies WHERE queue_mode = 'FORCE_OFF'"));
    }

    @Test
    void createsEverySeatAsAvailable() {
        seeder(true, 1).seedLoadTestFixture();

        assertEquals(2000, count(
                "SELECT COUNT(*) FROM performance_seats WHERE state = 'AVAILABLE'"));
    }

    @Test
    void appliesGradePricesToPerformanceSeats() {
        seeder(true, 1).seedLoadTestFixture();

        // 구역 1~2(좌석 1~400)는 VIP 150000, 마지막 구역은 A 60000이다.
        assertEquals(400, count(
                "SELECT COUNT(*) FROM performance_seats WHERE price = 150000"));
        assertEquals(600, count(
                "SELECT COUNT(*) FROM performance_seats WHERE price = 60000"));
    }

    @Test
    void doesNothingWhenDisabled() {
        seeder(false, 8).seedLoadTestFixture();

        assertEquals(0, count("SELECT COUNT(*) FROM seats"));
        assertEquals(0, count("SELECT COUNT(*) FROM performances"));
    }

    @Test
    void doesNothingWhenPerformanceCountIsNotPositive() {
        seeder(true, 0).seedLoadTestFixture();

        assertEquals(0, count("SELECT COUNT(*) FROM seats"));
        assertEquals(0, count("SELECT COUNT(*) FROM performances"));
    }

    @Test
    void isIdempotentWhenRunTwice() {
        seeder(true, 2).seedLoadTestFixture();
        seeder(true, 2).seedLoadTestFixture();

        assertEquals(2000, count("SELECT COUNT(*) FROM seats"));
        assertEquals(2, count("SELECT COUNT(*) FROM performances"));
        assertEquals(4000, count("SELECT COUNT(*) FROM performance_seats"));
    }
}
