-- Flyway 도입 이전(pre-Flyway) 기준 스키마다. 빈 DB에서 migration만으로 현재 스키마를 만들기 위해 둔다.
--
-- 운영은 이 파일을 실행하지 않는다. 운영 flyway_schema_history에는 version 1 BASELINE 행이 있어
-- (2026-05 Flyway 도입 때 기존 스키마를 baseline으로 등록) Flyway가 이 파일을 baseline 이하로 보고 건너뛴다.
-- 빈 DB(로컬·테스트)에서만 __root V2보다 먼저 실행된다.
--
-- 모양은 "지금 entity"가 아니라 "뒤따르는 migration이 전제하는 옛 모양"이다. 뒤 migration 중 일부가
-- 존재 확인 없이 컬럼·제약을 추가하므로(booking V3·V4 등), 그 대상은 여기서 빼 두고 해당 migration이 만든다.
--   - PERFORMANCES: 판매정책 컬럼 4개를 둔다(booking V6가 옮기고 지운다).
--   - PERFORMANCE_SEATS: performance_grade_id·unit_price·version이 없다(show V6·booking V3가 추가한다).
--   - ORDERS·ORDER_SEATS: 표시 snapshot 컬럼과 주문좌석 유니크가 없다(booking V4가 추가한다).
--   - 좌석 주소 유니크(venue V1), 찜 유니크(like V3), 회차좌석 유니크(root V3), 주문좌석 order_id 인덱스(root V4)는 각 migration이 만든다.
--   - GRADES·PERFORMANCE_GRADES(show V4), TICKETS(booking V5), BOOKING_PERFORMANCE_SALES_POLICIES(booking V6),
--     PAYMENTS(payment V1), EVENT_PUBLICATION(root V8)은 여기 없다.
-- 원본은 현재 entity 매핑에서 Hibernate schema export로 뽑은 DDL이다. 이 파일만이 아니라 전체 migration을 거친
-- 결과가 entity와 맞는지를 MigrationChainSchemaTest가 고정한다.

create table categories (
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        code varchar2(255 char) not null unique,
        created_by varchar2(255 char) not null,
        name varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table genres (
        category_id number(19,0) not null,
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        code varchar2(255 char) not null unique,
        created_by varchar2(255 char) not null,
        name varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table hold_history (
        created_at timestamp(9) not null,
        expires_at timestamp(9),
        id number(19,0) generated by default as identity,
        member_id number(19,0) not null,
        occurred_at timestamp(9) not null,
        performance_id number(19,0) not null,
        performance_seat_id number(19,0) not null,
        seat_id number(19,0) not null,
        updated_at timestamp(9),
        event_type varchar2(32 char) not null check ((event_type in ('CREATED','CONFIRMED','EXPIRED','CANCELED'))),
        release_reason varchar2(32 char) check ((release_reason in ('PAYMENT_CONFIRMED','TTL_EXPIRED','USER_CANCELED','ORDER_EXPIRED','PAYMENT_FAILED'))),
        hold_key varchar2(64 char) not null,
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table likes (
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        member_id number(19,0) not null,
        target_id number(19,0) not null,
        updated_at timestamp(9),
        like_type varchar2(20 char) not null check ((like_type in ('SHOW'))),
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table member_social_accounts (
        created_at timestamp(9) not null,
        deleted_at timestamp(9),
        id number(19,0) generated by default as identity,
        member_id number(19,0) not null,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        social_id varchar2(255 char) not null,
        social_provider varchar2(255 char) not null check ((social_provider in ('GOOGLE','KAKAO'))),
        updated_by varchar2(255 char),
        primary key (id),
        unique (social_provider, social_id),
        unique (member_id, social_provider)
    );

create table members (
        created_at timestamp(9) not null,
        deleted_at timestamp(9),
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        email varchar2(255 char),
        name varchar2(255 char),
        password varchar2(255 char),
        role varchar2(255 char) check ((role in ('ADMIN','MEMBER'))),
        updated_by varchar2(255 char),
        primary key (id),
        unique (email)
    );

create table order_seats (
        price number(19,2) not null,
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        order_id number(19,0) not null,
        performance_seat_id number(19,0) not null,
        seat_id number(19,0) not null,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table orders (
        total_amount number(19,2) not null,
        canceled_at timestamp(9),
        confirmed_at timestamp(9),
        created_at timestamp(9) not null,
        expired_at timestamp(9),
        expires_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        member_id number(19,0) not null,
        performance_id number(19,0) not null,
        updated_at timestamp(9),
        status varchar2(32 char) not null check ((status in ('PENDING','CONFIRMED','EXPIRED','CANCELED'))),
        order_key varchar2(40 char) not null unique,
        hold_key varchar2(64 char) not null unique,
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table performance_seats (
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        performance_id number(19,0) not null,
        seat_id number(19,0) not null,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        state varchar2(255 char) check ((state in ('AVAILABLE','RESERVED'))),
        updated_by varchar2(255 char),
        primary key (id)
    );

create table performances (
        created_at timestamp(9) not null,
        end_time timestamp(9),
        id number(19,0) generated by default as identity,
        performance_no number(19,0),
        show_id number(19,0),
        start_time timestamp(9),
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        order_open_time timestamp(9),
        order_close_time timestamp(9),
        max_can_hold_count number(10,0),
        hold_time number(10,0),
        primary key (id)
    );

create table performers (
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        name varchar2(255 char),
        profile_image_url varchar2(255 char),
        updated_by varchar2(255 char),
        primary key (id)
    );

create table seats (
        floor number(10,0) not null,
        x binary_double not null,
        y binary_double not null,
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        venue_id number(19,0) not null,
        created_by varchar2(255 char) not null,
        row_no varchar2(255 char) not null,
        seat_no varchar2(255 char) not null,
        section varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table show_genres (
        created_at timestamp(9) not null,
        genre_id number(19,0) not null,
        id number(19,0) generated by default as identity,
        show_id number(19,0) not null,
        updated_at timestamp(9),
        created_by varchar2(255 char) not null,
        updated_by varchar2(255 char),
        primary key (id)
    );

create table shows (
        end_date date,
        running_minutes number(10,0),
        start_date date,
        created_at timestamp(9) not null,
        display_sale_ends_at timestamp(9),
        display_sale_starts_at timestamp(9),
        id number(19,0) generated by default as identity,
        performer_id number(19,0),
        updated_at timestamp(9),
        venue_id number(19,0) not null,
        view_count number(19,0) not null,
        sub_title varchar2(500 char),
        title varchar2(1000 char),
        created_by varchar2(255 char) not null,
        display_sale_type varchar2(255 char) check ((display_sale_type in ('GENERAL','EXCLUSIVE'))),
        image varchar2(255 char),
        updated_by varchar2(255 char),
        info CLOB,
        primary key (id)
    );

create table venues (
        gap_x binary_double,
        gap_y binary_double,
        latitude number(10,8),
        longitude number(11,8),
        seat_diameter binary_double not null,
        view_box_height number(10,0) not null,
        view_box_width number(10,0) not null,
        created_at timestamp(9) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(9),
        address varchar2(255 char),
        address_detail varchar2(255 char),
        created_by varchar2(255 char) not null,
        image_url varchar2(255 char),
        name varchar2(255 char),
        phone varchar2(255 char),
        region varchar2(255 char) check ((region in ('SEOUL','GYEONGGI','INCHEON','GANGWON','CHUNGCHEONG','JEOLLA','GYEONGSANG','JEJU'))),
        updated_by varchar2(255 char),
        zip_code varchar2(255 char),
        primary key (id)
    );

create index IDX_HOLD_HISTORY_HOLD_KEY
       on hold_history (hold_key);

create index IDX_LIKES_MEMBER_ID_ID
       on likes (member_id, id);

create index IDX_LIKES_TARGET
       on likes (like_type, target_id);

create index IDX_ORDERS_MEMBER_PERFORMANCE_STATUS
       on orders (member_id, performance_id, status);

alter table member_social_accounts
       add constraint FK_MEMBER_SOCIAL_ACCOUNTS_MEMBER
       foreign key (member_id)
       references members;

alter table order_seats
       add constraint FK_ORDER_SEATS_ORDER
       foreign key (order_id)
       references orders;
