CREATE TABLE ORDER_HOLD_RELEASE_OUTBOX (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT NOT NULL,
    hold_key VARCHAR(64) NOT NULL,
    seat_ids_payload CLOB NOT NULL,
    next_attempt_at TIMESTAMP NOT NULL,
    retry_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX IDX_ORDER_HOLD_RELEASE_OUTBOX_DUE
    ON ORDER_HOLD_RELEASE_OUTBOX (status, next_attempt_at);
