CREATE TABLE PAYMENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_key VARCHAR(40) NOT NULL,
    order_id BIGINT NOT NULL,
    method VARCHAR(20) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    pg_transaction_id VARCHAR(64),
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_code VARCHAR(40),
    failure_message VARCHAR(200),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE UNIQUE INDEX UK_PAYMENTS_PAYMENT_KEY ON PAYMENTS (payment_key);

CREATE INDEX IDX_PAYMENTS_ORDER_ID ON PAYMENTS (order_id);
