-- ADR 0005: Grade는 재사용 가능한 등급 코드/이름만 갖고 가격이 없다. PerformanceGrade가 회차별
-- 가격·표시 순서를 갖는 연결 entity이며 가격의 원본이다
-- (PerformanceGrade.price -> PerformanceSeat.unitPrice -> OrderSeat.unitPrice snapshot 체인).
-- PERFORMANCES table은 어떤 Flyway migration도 만들지 않은 pre-Flyway baseline이라(docs/operations.md
-- 참고) 이미 존재한다는 전제로 FK를 건다.
--
-- 존재 확인 가드: `catalog` module이 `show`로 개명되며 이 파일이 새 Flyway 이력
-- (flyway_schema_history_show)으로 처음부터 다시 실행된다. dev/prod 환경은 이미 GRADES/
-- PERFORMANCE_GRADES가 존재하므로(옛 catalog 이력으로 적용됨) 재실행 시에도 ORA-00955 없이
-- 넘어가야 한다.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'GRADES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE GRADES (
                id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR2(255 CHAR) NOT NULL,
                name VARCHAR2(255 CHAR) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                created_by VARCHAR2(255 CHAR) NOT NULL,
                updated_at TIMESTAMP,
                updated_by VARCHAR2(255 CHAR),
                CONSTRAINT uk_grades_code UNIQUE (code)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'PERFORMANCE_GRADES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE PERFORMANCE_GRADES (
                id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                performance_id NUMBER(19, 0) NOT NULL,
                grade_id NUMBER(19, 0) NOT NULL,
                price NUMBER(19, 2) NOT NULL,
                sort_order NUMBER(10, 0) NOT NULL,
                created_at TIMESTAMP NOT NULL,
                created_by VARCHAR2(255 CHAR) NOT NULL,
                updated_at TIMESTAMP,
                updated_by VARCHAR2(255 CHAR),
                CONSTRAINT fk_performance_grades_performance FOREIGN KEY (performance_id) REFERENCES PERFORMANCES (id),
                CONSTRAINT fk_performance_grades_grade FOREIGN KEY (grade_id) REFERENCES GRADES (id),
                CONSTRAINT uk_performance_grades_performance_grade UNIQUE (performance_id, grade_id),
                CONSTRAINT ck_performance_grades_price CHECK (price >= 0)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IDX_PERFORMANCE_GRADES_PERF_SORT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_performance_grades_perf_sort ON PERFORMANCE_GRADES (performance_id, sort_order)';
    END IF;
END;
/
