-- PostgreSQL 전환 시 새 DB에 적용하는 show 소유 초기 스키마다.
-- 기존 H2/Oracle 전체 migration 결과의 컬럼·제약을 보존하며, 과거 Flyway 이력은 가져오지 않는다.

CREATE TABLE categories(
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    code VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255)
);

ALTER TABLE categories ADD CONSTRAINT pk_categories PRIMARY KEY(id);

CREATE TABLE genres(
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    code VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255)
);

ALTER TABLE genres ADD CONSTRAINT pk_genres PRIMARY KEY(id);

CREATE TABLE performances(
    created_at TIMESTAMP(6) NOT NULL,
    end_time TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    performance_no BIGINT,
    show_id BIGINT,
    start_time TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255)
);

ALTER TABLE performances ADD CONSTRAINT pk_performances PRIMARY KEY(id);

CREATE TABLE performers(
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    profile_image_url VARCHAR(255),
    updated_by VARCHAR(255)
);

ALTER TABLE performers ADD CONSTRAINT pk_performers PRIMARY KEY(id);

CREATE TABLE show_genres(
    created_at TIMESTAMP(6) NOT NULL,
    genre_id BIGINT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    show_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255)
);

ALTER TABLE show_genres ADD CONSTRAINT pk_show_genres PRIMARY KEY(id);

CREATE TABLE shows(
    end_date DATE,
    running_minutes INTEGER,
    start_date DATE,
    created_at TIMESTAMP(6) NOT NULL,
    display_sale_ends_at TIMESTAMP(6),
    display_sale_starts_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    performer_id BIGINT,
    updated_at TIMESTAMP(6),
    venue_id BIGINT NOT NULL,
    view_count BIGINT NOT NULL,
    sub_title VARCHAR(500),
    title VARCHAR(1000),
    created_by VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    updated_by VARCHAR(255),
    display_sale_type VARCHAR(255) CHECK (display_sale_type IN ('EXCLUSIVE', 'GENERAL')),
    info TEXT
);

ALTER TABLE shows ADD CONSTRAINT pk_shows PRIMARY KEY(id);

CREATE TABLE grades(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

ALTER TABLE grades ADD CONSTRAINT pk_grades PRIMARY KEY(id);

CREATE TABLE performance_grades(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    performance_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

ALTER TABLE performance_grades ADD CONSTRAINT pk_performance_grades PRIMARY KEY(id);

ALTER TABLE performance_grades ADD CONSTRAINT ck_performance_grades_price CHECK(price >= CAST(0 AS NUMERIC(1)));

ALTER TABLE grades ADD CONSTRAINT uk_grades_code UNIQUE (code);

ALTER TABLE categories ADD CONSTRAINT uk_categories_code UNIQUE (code);

ALTER TABLE genres ADD CONSTRAINT uk_genres_code UNIQUE (code);

ALTER TABLE performance_grades ADD CONSTRAINT uk_performance_grades_performance_grade UNIQUE (performance_id, grade_id);

ALTER TABLE performance_grades ADD CONSTRAINT fk_performance_grades_grade FOREIGN KEY(grade_id) REFERENCES grades(id);

ALTER TABLE performance_grades ADD CONSTRAINT fk_performance_grades_performance FOREIGN KEY(performance_id) REFERENCES performances(id);
