CREATE TABLE ORDER_HOLD_RELEASE_OUTBOX (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id NUMBER(19, 0) NOT NULL,
    hold_key VARCHAR2(64) NOT NULL,
    seat_ids_payload CLOB NOT NULL,
    next_attempt_at TIMESTAMP NOT NULL,
    retry_count NUMBER(10, 0) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    completed_at TIMESTAMP,
    last_error VARCHAR2(1000),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR2(255)
);

CREATE INDEX IDX_ORDER_HOLD_RELEASE_OUTBOX_DUE
    ON ORDER_HOLD_RELEASE_OUTBOX (status, next_attempt_at);
