CREATE TABLE PAYMENTS (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_key VARCHAR2(40) NOT NULL,
    order_id NUMBER(19, 0) NOT NULL,
    method VARCHAR2(20) NOT NULL,
    amount NUMBER(19, 2) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    pg_transaction_id VARCHAR2(64),
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_code VARCHAR2(40),
    failure_message VARCHAR2(200),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR2(255)
);

CREATE UNIQUE INDEX UK_PAYMENTS_PAYMENT_KEY ON PAYMENTS (payment_key);

CREATE INDEX IDX_PAYMENTS_ORDER_ID ON PAYMENTS (order_id);
