-- ADR 0005: Ticket은 결제 성공으로 확정된 OrderSeat에 대해 발급되는 입장 권리다
-- (OrderSeat 1 : 0..1 Ticket). ticketing은 booking/identity를 참조하지 않는 독립 module이므로
-- order_seat_id/owner_member_id는 scalar 컬럼일 뿐 FK를 걸지 않는다
-- (cross-module 물리 FK 금지, ADR 0003/0005).
CREATE TABLE TICKETS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_key VARCHAR(64) NOT NULL,
    order_seat_id BIGINT NOT NULL,
    owner_member_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT uk_tickets_ticket_key UNIQUE (ticket_key),
    CONSTRAINT uk_tickets_order_seat_id UNIQUE (order_seat_id)
);

CREATE INDEX idx_tickets_owner_member_status ON TICKETS (owner_member_id, status);
